package br.edu.ifsp.pep.locadoraveiculo.visao;

import br.edu.ifsp.pep.locadoraveiculo.dao.LocacaoDAO;
import br.edu.ifsp.pep.locadoraveiculo.dao.VeiculoDAO;
import br.edu.ifsp.pep.locadoraveiculo.modelo.Locacao;
import br.edu.ifsp.pep.locadoraveiculo.modelo.Veiculo;
import br.edu.ifsp.pep.locadoraveiculo.modelo.VeiculoLocado;
import br.edu.ifsp.pep.locadoraveiculo.utilitarios.Mensagem;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class LocacaoView extends javax.swing.JDialog {

    private final Mensagem mensagem = new Mensagem();
    private Date hoje = new Date();
    private VeiculoDAO veiculoDAO = new VeiculoDAO();
    private List<Veiculo> listaVeiculos = new ArrayList<>();

    public LocacaoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.atualizarComboBoxVeiculos();
        this.setDataAtual();
    }

    private void atualizarComboBoxVeiculos() {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.comboVeiculos.getModel();
        modelo.addAll(veiculoDAO.buscarVeiculosDisponiveisParaLocacao());
        this.comboVeiculos.setSelectedIndex(-1);
    }

    private void setDataAtual() {
        this.jCalendarData.setDate(this.hoje);
    }

    private void atualizarTabelaResumoLocacao() {
        DefaultTableModel modelo = (DefaultTableModel) this.tabelaResumoLocacao.getModel();
        modelo.setNumRows(0);

        for (Veiculo veiculo : listaVeiculos) {
            modelo.addRow(new Object[]{
                veiculo.getModelo(), veiculo.getPlaca(),
                veiculo.getTipo().getValorDiaria(), this.spinnerQtdDias.getValue()
            });
        }
    }

    private void resetCampos() {
        this.txtCliente.setText("");
        this.setDataAtual();
        this.comboVeiculos.setSelectedIndex(-1);
        this.spinnerQtdDias.setValue(1);
        this.listaVeiculos.removeAll(listaVeiculos);
        this.atualizarTabelaResumoLocacao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitulo = new javax.swing.JPanel();
        labelLocacao = new javax.swing.JLabel();
        painelDados = new javax.swing.JPanel();
        labelCliente = new javax.swing.JLabel();
        labelVeiculo = new javax.swing.JLabel();
        labelQtdDias = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        comboVeiculos = new javax.swing.JComboBox<>();
        spinnerQtdDias = new javax.swing.JSpinner();
        btnAdicionar = new javax.swing.JButton();
        txtCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaResumoLocacao = new javax.swing.JTable();
        jCalendarData = new com.toedter.calendar.JDateChooser();
        painelBotoes = new javax.swing.JPanel();
        btnFinalizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        painelTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelLocacao.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        labelLocacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLocacao.setText("Locação");

        javax.swing.GroupLayout painelTituloLayout = new javax.swing.GroupLayout(painelTitulo);
        painelTitulo.setLayout(painelTituloLayout);
        painelTituloLayout.setHorizontalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLocacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelTituloLayout.setVerticalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLocacao)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        painelDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelCliente.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        labelCliente.setText("Cliente");

        labelVeiculo.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        labelVeiculo.setText("Veículo");

        labelQtdDias.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        labelQtdDias.setText("Qtd Dias");

        labelData.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        labelData.setText("Data");

        comboVeiculos.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N

        spinnerQtdDias.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        spinnerQtdDias.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btnAdicionar.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        txtCliente.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N

        tabelaResumoLocacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Placa", "Valor Diária", "Qtd. Dias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaResumoLocacao.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabelaResumoLocacao);
        if (tabelaResumoLocacao.getColumnModel().getColumnCount() > 0) {
            tabelaResumoLocacao.getColumnModel().getColumn(0).setResizable(false);
            tabelaResumoLocacao.getColumnModel().getColumn(1).setResizable(false);
            tabelaResumoLocacao.getColumnModel().getColumn(2).setResizable(false);
            tabelaResumoLocacao.getColumnModel().getColumn(3).setResizable(false);
        }

        jCalendarData.setDateFormatString("d '/' MM '/' y");
        jCalendarData.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N

        javax.swing.GroupLayout painelDadosLayout = new javax.swing.GroupLayout(painelDados);
        painelDados.setLayout(painelDadosLayout);
        painelDadosLayout.setHorizontalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                    .addGroup(painelDadosLayout.createSequentialGroup()
                        .addComponent(labelVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboVeiculos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelDadosLayout.createSequentialGroup()
                        .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosLayout.createSequentialGroup()
                                .addComponent(labelData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCalendarData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosLayout.createSequentialGroup()
                                .addComponent(labelQtdDias, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spinnerQtdDias, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdicionar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelDadosLayout.createSequentialGroup()
                        .addComponent(labelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCliente)))
                .addContainerGap())
        );
        painelDadosLayout.setVerticalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelData, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCalendarData, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQtdDias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerQtdDias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelBotoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnFinalizar.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        btnExcluir.setText("Excluir Veículo");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBotoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // Capturando o Veículo selecionado no combo box
        Veiculo selecionado = (Veiculo) this.comboVeiculos.getSelectedItem();

        // Verificando se foi selecionado um Veículo, se for diferente de nulo
        if (selecionado != null) {

            // Verificando se o Veículo selecionado já foi ou não inserido no resumo
            if (this.listaVeiculos.contains(selecionado)) {
                this.mensagem.mAtencao("Veículo já adicionado.\nEscolha outro veículo");
            } else {
                this.listaVeiculos.add((Veiculo) this.comboVeiculos.getSelectedItem());
                this.atualizarTabelaResumoLocacao();
                this.comboVeiculos.setSelectedIndex(-1);
            }
        } else {
            this.mensagem.mAviso("Selecione um veículo para locar");
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        boolean tudoOK = true;
        int diasLocado = (int) this.spinnerQtdDias.getValue();

        if (this.txtCliente.getText().isEmpty()) {
            this.mensagem.mAviso("Informe um Cliente");
            this.txtCliente.requestFocus();
            tudoOK = false;
        }

        if (this.hoje.after(this.jCalendarData.getDate())) {
            this.mensagem.mAviso("Informe uma data válida");
            this.jCalendarData.requestFocus();
            tudoOK = false;
        }

        if (this.listaVeiculos.isEmpty()) {
            this.mensagem.mAviso("Nenhum Veículo locado");
            this.comboVeiculos.requestFocus();
            tudoOK = false;
        }

        if (tudoOK) {
            if (this.mensagem.mSimNao("Finalizar?")) {
                System.out.println("OK -- Gravou");
//                BigDecimal valorTotalLocacao = BigDecimal.ZERO;
//                Locacao locacao = new Locacao();
//                LocacaoDAO locacaoDAO = new LocacaoDAO();
//                VeiculoLocado veiculoLocado;
//                List<VeiculoLocado> listaVeiculosLocado = new ArrayList<>();
//
//                // Inserindo Veículos selecionados na lista de VeiculosLocados
//                for (Veiculo veiculo : this.listaVeiculos) {
//                    veiculoLocado = new VeiculoLocado(veiculo,
//                            locacao,
//                            diasLocado);
//                    listaVeiculosLocado.add(veiculoLocado);
//                    valorTotalLocacao.add((veiculo.getTipo().getValorDiaria().
//                            multiply(new BigDecimal(diasLocado))));
//                }
//                // Variavél global Cliente
//                locacao.setCliente(cliente);
//                locacao.setData(this.jCalendarData.getDate());
//                locacao.setVeiculosLocado(listaVeiculosLocado);
//                try {
//                    locacaoDAO.inserir(locacao);
//                    this.mensagem.mInformacao("Total da Locação: R$ " + valorTotalLocacao);
                this.resetCampos();
//                } catch (Exception e) {
//                    this.mensagem.mErro(e.getMessage());
//                }
            }
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // Capturando o Veículo selecionado no combo box
        Veiculo selecionado = this.listaVeiculos.
                get(this.tabelaResumoLocacao.getSelectedRow());

        // Verificando se foi selecionado um Veículo, se for diferente de nulo
        if (selecionado != null) {
            // Se confirmar a exclusão, remove da lista
            if (this.mensagem.mSimNao("Confimar exclsão?")) {
                this.listaVeiculos.remove(selecionado);
                this.atualizarTabelaResumoLocacao();
                this.comboVeiculos.setSelectedIndex(-1);
            }
        } else {
            this.mensagem.mAviso("Selecione um veículo para excluir");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (this.mensagem.mConfimarCancelar("Confimar?")) {
            this.resetCampos();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LocacaoView dialog = new LocacaoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JComboBox<String> comboVeiculos;
    private com.toedter.calendar.JDateChooser jCalendarData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelLocacao;
    private javax.swing.JLabel labelQtdDias;
    private javax.swing.JLabel labelVeiculo;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelDados;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JSpinner spinnerQtdDias;
    private javax.swing.JTable tabelaResumoLocacao;
    private javax.swing.JTextField txtCliente;
    // End of variables declaration//GEN-END:variables
}
