package br.edu.ifsp.pep.locadoraveiculo.visao;

import br.edu.ifsp.pep.locadoraveiculo.dao.TipoVeiculoDAO;
import br.edu.ifsp.pep.locadoraveiculo.dao.VeiculoDAO;
import br.edu.ifsp.pep.locadoraveiculo.modelo.TipoVeiculo;
import br.edu.ifsp.pep.utilitarios.Mensagem;
import br.edu.ifsp.pep.utilitarios.Relatorio;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

public class RelatorioVeiculoView extends javax.swing.JDialog {

    public RelatorioVeiculoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.atualizarComboBoxTipoVeiculo();
        this.setLocationRelativeTo(null);
    }

    private void atualizarComboBoxTipoVeiculo() {
        TipoVeiculoDAO tipoVeiculoDAO = new TipoVeiculoDAO();
        List<TipoVeiculo> listaTiposVeiculos = tipoVeiculoDAO.retonarTodos();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.comboBoxTipoVeiculo.getModel();
        modelo.addElement("");
        for (TipoVeiculo tipo : listaTiposVeiculos) {
            modelo.addElement(tipo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        separadorTitulo = new javax.swing.JSeparator();
        labelTipoVeiculo = new javax.swing.JLabel();
        comboBoxTipoVeiculo = new javax.swing.JComboBox<>();
        labelEOU = new javax.swing.JLabel();
        labelModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        btnGerarRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório Veículos");
        setMaximumSize(new java.awt.Dimension(1200, 960));
        setMinimumSize(new java.awt.Dimension(400, 320));
        setPreferredSize(new java.awt.Dimension(400, 320));

        painelGeral.setMinimumSize(new java.awt.Dimension(388, 308));

        labelTitulo.setFont(new java.awt.Font("Fira Sans", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(51, 51, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Relatório Veículos");

        labelTipoVeiculo.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        labelTipoVeiculo.setText("Tipo de Veículo");

        comboBoxTipoVeiculo.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        comboBoxTipoVeiculo.setMinimumSize(new java.awt.Dimension(250, 40));
        comboBoxTipoVeiculo.setPreferredSize(new java.awt.Dimension(250, 40));

        labelEOU.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        labelEOU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEOU.setText("e /ou");

        labelModelo.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        labelModelo.setText("Modelo");

        txtModelo.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N

        btnGerarRelatorio.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        btnGerarRelatorio.setText("Gerar Relatório");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelGeralLayout = new javax.swing.GroupLayout(painelGeral);
        painelGeral.setLayout(painelGeralLayout);
        painelGeralLayout.setHorizontalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEOU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(separadorTitulo)
                    .addGroup(painelGeralLayout.createSequentialGroup()
                        .addComponent(labelTipoVeiculo)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxTipoVeiculo, 0, 1, Short.MAX_VALUE))
                    .addGroup(painelGeralLayout.createSequentialGroup()
                        .addComponent(labelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelGeralLayout.createSequentialGroup()
                                .addComponent(btnGerarRelatorio)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtModelo))))
                .addContainerGap())
        );
        painelGeralLayout.setVerticalGroup(
            painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEOU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        String fileXML = "RelatorioVeiculo.jrxml";
        int opcaoComboBox = this.comboBoxTipoVeiculo.getSelectedIndex();
        String textoModelo = this.txtModelo.getText();
        VeiculoDAO veiculoDAO = new VeiculoDAO();

        if (opcaoComboBox != 0) {
            TipoVeiculo tipoVeiculo = (TipoVeiculo) this.comboBoxTipoVeiculo.getSelectedItem();
            if (textoModelo.equals("")) {

                // Pesquisar apenas por TIPO VEÍCULO
                Relatorio.gerarFromXML(fileXML,
                        veiculoDAO.buscarPorTipoVeiculo(tipoVeiculo.getId()));
            } else {
                // Pesquisar por TIPO VEÍCULO E MODELO
                Relatorio.gerarFromXML(fileXML,
                        veiculoDAO.buscarPorModeloETipoVeiculo(textoModelo, tipoVeiculo.getId()));
            }
        } else {
            if (!(textoModelo.equals(""))) {
                // Pesquisar por apenas por MODELO
                Relatorio.gerarFromXML(fileXML,
                        veiculoDAO.buscarPorModelo(textoModelo));
            } else {
                Mensagem.mAviso("Escolha um Tipo de Veículo e/ou informe um Modelo");
            }
        }
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RelatorioVeiculoView dialog = new RelatorioVeiculoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JComboBox<String> comboBoxTipoVeiculo;
    private javax.swing.JLabel labelEOU;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelTipoVeiculo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JSeparator separadorTitulo;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
