package br.edu.ifsp.pep.locadoraveiculo.visao;

import br.edu.ifsp.pep.locadoraveiculo.dao.TipoVeiculoDAO;
import br.edu.ifsp.pep.locadoraveiculo.dao.VeiculoDAO;
import br.edu.ifsp.pep.locadoraveiculo.modelo.TipoVeiculo;
import br.edu.ifsp.pep.locadoraveiculo.modelo.Veiculo;
import br.edu.ifsp.pep.locadoraveiculo.utilitarios.Mensagem;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class VeiculoView extends javax.swing.JDialog {

    private final Mensagem mensagem = new Mensagem();
    private static final VeiculoDAO veiculoDAO = new VeiculoDAO();
    private List<Veiculo> listaVeiculos;
    private Veiculo veiculo;
    private static final TipoVeiculoDAO tipoVeiculoDAO = new TipoVeiculoDAO();
    private List<TipoVeiculo> listaTiposVeiculos;

    public VeiculoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.atualizarComboBoxTipoVeiculo();
        this.comboTipoVeiculo.setSelectedIndex(-1);
    }

    private void setEstadoBotoes(boolean estado) {
        this.btnInserir.setEnabled(estado);
        this.btnAlterar.setEnabled(estado);
        this.btnExcluir.setEnabled(estado);
        this.btnPesquisa.setEnabled(estado);
        this.txtPesquisar.setEnabled(estado);
    }

    private void setEstadoCamposTexto(boolean estado) {
        this.txtModelo.setEnabled(estado);
        this.txtPlaca.setEnabled(estado);
        this.txtAno.setEnabled(estado);
        this.txtCidade.setEnabled(estado);
        this.comboTipoVeiculo.setEnabled(estado);
    }

    private void atualizarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.tabelaVeiculos.getModel();
        modelo.setNumRows(0);

        for (Veiculo veiculo : listaVeiculos) {
            modelo.addRow(new Object[]{veiculo.getModelo(), veiculo.getAno(),
                veiculo.getPlaca(), veiculo.getLocado(), veiculo.getTipo().getNome(),
                veiculo.getTipo().getValorDiaria()
            });
        }
    }

    private void limparCampos() {
        this.txtModelo.setText("");
        this.txtAno.setText("");
        this.txtPlaca.setText("");
        this.txtCidade.setText("");
        this.comboTipoVeiculo.setSelectedIndex(-1);
    }

    private void atualizarComboBoxTipoVeiculo() {
        this.listaTiposVeiculos = tipoVeiculoDAO.retonarTodos();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.comboTipoVeiculo.getModel();
        for (TipoVeiculo tipo : this.listaTiposVeiculos) {
            modelo.addElement(tipo.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitulo = new javax.swing.JPanel();
        labelVeiculos = new javax.swing.JLabel();
        tabPainel = new javax.swing.JTabbedPane();
        tabPesquisar = new javax.swing.JPanel();
        labelDescricao = new javax.swing.JLabel();
        btnPesquisa = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVeiculos = new javax.swing.JTable();
        painelBotoesPesquisa = new javax.swing.JPanel();
        btnAlterar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        tabCadastro = new javax.swing.JPanel();
        labelModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        labelPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JFormattedTextField();
        comboTipoVeiculo = new javax.swing.JComboBox<>();
        labelTipoVeiculo = new javax.swing.JLabel();
        labelAno = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        painelBotoesCadastro = new javax.swing.JPanel();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        labelCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelVeiculos.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        labelVeiculos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVeiculos.setText("Veículos");

        javax.swing.GroupLayout painelTituloLayout = new javax.swing.GroupLayout(painelTitulo);
        painelTitulo.setLayout(painelTituloLayout);
        painelTituloLayout.setHorizontalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVeiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelTituloLayout.setVerticalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVeiculos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPainel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabPainel.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N

        labelDescricao.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        labelDescricao.setText("Descrição");

        btnPesquisa.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        tabelaVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Ano", "Placa", "Locado", "Tipo", "Valor Diária"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaVeiculos.setColumnSelectionAllowed(true);
        tabelaVeiculos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tabelaVeiculos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabelaVeiculos);
        tabelaVeiculos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabelaVeiculos.getColumnModel().getColumnCount() > 0) {
            tabelaVeiculos.getColumnModel().getColumn(0).setResizable(false);
            tabelaVeiculos.getColumnModel().getColumn(1).setResizable(false);
            tabelaVeiculos.getColumnModel().getColumn(2).setResizable(false);
            tabelaVeiculos.getColumnModel().getColumn(3).setResizable(false);
            tabelaVeiculos.getColumnModel().getColumn(4).setResizable(false);
            tabelaVeiculos.getColumnModel().getColumn(5).setResizable(false);
        }

        painelBotoesPesquisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAlterar.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnInserir.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInserir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesPesquisaLayout = new javax.swing.GroupLayout(painelBotoesPesquisa);
        painelBotoesPesquisa.setLayout(painelBotoesPesquisaLayout);
        painelBotoesPesquisaLayout.setHorizontalGroup(
            painelBotoesPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelBotoesPesquisaLayout.setVerticalGroup(
            painelBotoesPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelBotoesPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabPesquisarLayout = new javax.swing.GroupLayout(tabPesquisar);
        tabPesquisar.setLayout(tabPesquisarLayout);
        tabPesquisarLayout.setHorizontalGroup(
            tabPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addGroup(tabPesquisarLayout.createSequentialGroup()
                        .addComponent(labelDescricao)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisa))
                    .addComponent(painelBotoesPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tabPesquisarLayout.setVerticalGroup(
            tabPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescricao)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelBotoesPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tabPainel.addTab("Pesquisa", tabPesquisar);

        labelModelo.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        labelModelo.setText("Modelo");

        txtModelo.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N

        labelPlaca.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        labelPlaca.setText("Placa");

        try {
            txtPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAA-AAAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPlaca.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        labelTipoVeiculo.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        labelTipoVeiculo.setText("Tipo Veículo");

        labelAno.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        labelAno.setText("Ano");

        txtAno.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N

        painelBotoesCadastro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnGravar.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesCadastroLayout = new javax.swing.GroupLayout(painelBotoesCadastro);
        painelBotoesCadastro.setLayout(painelBotoesCadastroLayout);
        painelBotoesCadastroLayout.setHorizontalGroup(
            painelBotoesCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelBotoesCadastroLayout.setVerticalGroup(
            painelBotoesCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btnGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        labelCidade.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        labelCidade.setText("Cidade");

        txtCidade.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N

        javax.swing.GroupLayout tabCadastroLayout = new javax.swing.GroupLayout(tabCadastro);
        tabCadastro.setLayout(tabCadastroLayout);
        tabCadastroLayout.setHorizontalGroup(
            tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelBotoesCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabCadastroLayout.createSequentialGroup()
                        .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabCadastroLayout.createSequentialGroup()
                                .addComponent(labelCidade)
                                .addGap(18, 18, 18)
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabCadastroLayout.createSequentialGroup()
                                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelModelo)
                                    .addComponent(labelPlaca)
                                    .addComponent(labelAno))
                                .addGap(18, 18, 18)
                                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtAno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(txtPlaca, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(tabCadastroLayout.createSequentialGroup()
                                .addComponent(labelTipoVeiculo)
                                .addGap(43, 43, 43)
                                .addComponent(comboTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 216, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabCadastroLayout.setVerticalGroup(
            tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPlaca))
                .addGap(18, 18, 18)
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAno)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipoVeiculo))
                .addGap(18, 18, 18)
                .addComponent(painelBotoesCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tabPainel.addTab("Cadastro", tabCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPainel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (this.tabelaVeiculos.getSelectedRow() >= 0) {
            this.veiculo = this.listaVeiculos.get(
                    this.tabelaVeiculos.getSelectedRow());

            this.txtModelo.setText(this.veiculo.getModelo());
            this.txtAno.setText(String.valueOf(this.veiculo.getAno()));
            this.txtPlaca.setText(this.veiculo.getPlaca());
            this.txtCidade.setText(this.veiculo.getCidade());
            this.comboTipoVeiculo.setSelectedItem(this.veiculo.getTipo().getNome());

            this.setEstadoBotoes(false);
            this.tabPainel.setSelectedIndex(1);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        listaVeiculos = veiculoDAO.buscarPorModelo(txtPesquisar.getText());
        this.atualizarTabela();

    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setEstadoBotoes(true);
        this.tabPainel.setSelectedIndex(0);
        this.limparCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        String mensagem = "Veículo cadastrado";
        boolean tudoOK = true;
        int anoInformado = 0;

        if (this.txtModelo.getText().isEmpty()) {
            this.mensagem.mAtencao("Modelo não informado");
            this.txtModelo.requestFocus();
            tudoOK = false;
        }

        if (this.txtPlaca.getText().isEmpty()) {
            this.mensagem.mAtencao("Placa não informado");
            this.txtPlaca.requestFocus();
            tudoOK = false;
        }

        try {
            anoInformado = Integer.parseInt(this.txtAno.getText());

        } catch (NumberFormatException nfe) {
            this.mensagem.mErro("Formato inválido. Informe um valor numérico");
            this.txtAno.requestFocus();
            tudoOK = false;
        }

        // Não está fazendo essa verificação
        System.out.println(anoInformado);
        if ((anoInformado < 1900) && (anoInformado > (new Date().getYear() + 1900))) {
            this.mensagem.mAviso("Ano informado inválido");
            this.txtAno.requestFocus();
            tudoOK = false;
        }

        if (this.txtCidade.getText()
                .isEmpty()) {
            this.mensagem.mAtencao("Infome uma Cidade");
            this.txtCidade.requestFocus();
            tudoOK = false;
        }

        if (this.comboTipoVeiculo.getSelectedIndex() < 0) {
            this.mensagem.mAtencao("Selecione um Tipo de Veículo");
            tudoOK = false;
        }

        if (tudoOK) {
            // Propagar no Banco de Dados se não houver informações faltantes ou incorretas

            // Verifica se está realizando uma exclusão, comparando o texto do botão
            if (this.btnGravar.getText().equals("Excluir")) {
                mensagem = "Veículo excluído";
                try {
                    veiculoDAO.remover(veiculo);
                    this.mensagem.mCorreto(mensagem);
                    this.limparCampos();
                } catch (Exception e) {
                    this.mensagem.mErro(e.getMessage());
                } finally {
                    this.veiculo = null;
                }

                // Se o texto não foi alterado, é uma inserção ou alteração
            } else {
                // Realizando uma inserção
                if (this.veiculo == null) {
                    this.veiculo = new Veiculo(
                            this.txtPlaca.getText(),
                            this.txtCidade.getText(),
                            this.txtModelo.getText(),
                            anoInformado,
                            this.listaTiposVeiculos.get(
                                    this.comboTipoVeiculo.getSelectedIndex()));
                } else {
                    // Realizando uma alteração
                    this.veiculo.setPlaca(this.txtPlaca.getText());
                    this.veiculo.setCidade(this.txtCidade.getText());
                    this.veiculo.setModelo(this.txtModelo.getText());
                    this.veiculo.setAno(anoInformado);
                    this.veiculo.setTipo(this.listaTiposVeiculos.get(
                            this.comboTipoVeiculo.getSelectedIndex()));
                    mensagem = "Veículo alterado";
                }

                // Propagando no banco a alteração ou inserção
                try {
                    veiculoDAO.alterar(this.veiculo);
                    this.mensagem.mCorreto(mensagem);
                    this.limparCampos();
                    this.setEstadoBotoes(true);

                } catch (Exception e) {
                    this.mensagem.mErro(e.getMessage());
                } finally {
                    this.veiculo = null;
                }
            }
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        this.limparCampos();
        this.tabPainel.setSelectedIndex(1);
        this.txtModelo.requestFocus();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (this.tabelaVeiculos.getSelectedRow() >= 0) {
            this.veiculo = this.listaVeiculos.get(
                    this.tabelaVeiculos.getSelectedRow());

            this.txtModelo.setText(this.veiculo.getModelo());
            this.txtAno.setText(String.valueOf(this.veiculo.getAno()));
            this.txtPlaca.setText(this.veiculo.getPlaca());
            this.txtCidade.setText(this.veiculo.getCidade());
            this.comboTipoVeiculo.setSelectedItem(this.veiculo.getTipo().getNome());

            this.setEstadoBotoes(false);
            this.setEstadoCamposTexto(false);
            this.btnGravar.setText("Excluir");
            this.tabPainel.setSelectedIndex(1);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeiculoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VeiculoView dialog = new VeiculoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JComboBox<String> comboTipoVeiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelPlaca;
    private javax.swing.JLabel labelTipoVeiculo;
    private javax.swing.JLabel labelVeiculos;
    private javax.swing.JPanel painelBotoesCadastro;
    private javax.swing.JPanel painelBotoesPesquisa;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JPanel tabCadastro;
    private javax.swing.JTabbedPane tabPainel;
    private javax.swing.JPanel tabPesquisar;
    private javax.swing.JTable tabelaVeiculos;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JFormattedTextField txtPlaca;
    // End of variables declaration//GEN-END:variables

}
